apiVersion: v2
name: workflow
version: v0.1.0
appVersion: v0.1.0
description: Fabrikam Drone Delivery Workflow Service
type: application
home: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks
sources:
  - https://github.com/mspnp/microservices-reference-implementation
dependencies:
  - name: workflow-dev
    repository: "file://envs/workflow-dev"
    version: v0.1.0
    condition: envs.dev
    import-values:
      - data

  - name: workflow-prod
    repository: "file://envs/workflow-prod"
    version: v0.1.0
    condition: envs.prod
    import-values:
      - data

  - name: workflow-qa
    repository: "file://envs/workflow-qa"
    version: v0.1.0
    condition: envs.qa
    import-values:
      - data

  - name: workflow-staging
    repository: "file://envs/workflow-staging"
    version: v0.1.0
    condition: envs.staging
    import-values:
      - data
maintainers:
  - email: v-fean@microsoft.com
    name: ferantivero
